use super::addressing::AddressingMode;

pub struct OpCode {
    pub mnemonic: &'static str,
    pub bytes: u8,
    pub cycles: u8,
    pub mode: AddressingMode,
}

/// All 256 opcodes. Unofficial ones are included with approximate timing.
pub static OPCODES: [OpCode; 256] = {
    use AddressingMode::*;

    const fn op(mnemonic: &'static str, bytes: u8, cycles: u8, mode: AddressingMode) -> OpCode {
        OpCode { mnemonic, bytes, cycles, mode }
    }

    [
        // 0x00
        op("BRK", 1, 7, Implied),
        op("ORA", 2, 6, IndirectX),
        op("KIL", 1, 2, Implied),
        op("SLO", 2, 8, IndirectX),
        op("NOP", 2, 3, ZeroPage),
        op("ORA", 2, 3, ZeroPage),
        op("ASL", 2, 5, ZeroPage),
        op("SLO", 2, 5, ZeroPage),
        op("PHP", 1, 3, Implied),
        op("ORA", 2, 2, Immediate),
        op("ASL", 1, 2, Accumulator),
        op("ANC", 2, 2, Immediate),
        op("NOP", 3, 4, Absolute),
        op("ORA", 3, 4, Absolute),
        op("ASL", 3, 6, Absolute),
        op("SLO", 3, 6, Absolute),
        // 0x10
        op("BPL", 2, 2, Relative),
        op("ORA", 2, 5, IndirectY),
        op("KIL", 1, 2, Implied),
        op("SLO", 2, 8, IndirectY),
        op("NOP", 2, 4, ZeroPageX),
        op("ORA", 2, 4, ZeroPageX),
        op("ASL", 2, 6, ZeroPageX),
        op("SLO", 2, 6, ZeroPageX),
        op("CLC", 1, 2, Implied),
        op("ORA", 3, 4, AbsoluteY),
        op("NOP", 1, 2, Implied),
        op("SLO", 3, 7, AbsoluteY),
        op("NOP", 3, 4, AbsoluteX),
        op("ORA", 3, 4, AbsoluteX),
        op("ASL", 3, 7, AbsoluteX),
        op("SLO", 3, 7, AbsoluteX),
        // 0x20
        op("JSR", 3, 6, Absolute),
        op("AND", 2, 6, IndirectX),
        op("KIL", 1, 2, Implied),
        op("RLA", 2, 8, IndirectX),
        op("BIT", 2, 3, ZeroPage),
        op("AND", 2, 3, ZeroPage),
        op("ROL", 2, 5, ZeroPage),
        op("RLA", 2, 5, ZeroPage),
        op("PLP", 1, 4, Implied),
        op("AND", 2, 2, Immediate),
        op("ROL", 1, 2, Accumulator),
        op("ANC", 2, 2, Immediate),
        op("BIT", 3, 4, Absolute),
        op("AND", 3, 4, Absolute),
        op("ROL", 3, 6, Absolute),
        op("RLA", 3, 6, Absolute),
        // 0x30
        op("BMI", 2, 2, Relative),
        op("AND", 2, 5, IndirectY),
        op("KIL", 1, 2, Implied),
        op("RLA", 2, 8, IndirectY),
        op("NOP", 2, 4, ZeroPageX),
        op("AND", 2, 4, ZeroPageX),
        op("ROL", 2, 6, ZeroPageX),
        op("RLA", 2, 6, ZeroPageX),
        op("SEC", 1, 2, Implied),
        op("AND", 3, 4, AbsoluteY),
        op("NOP", 1, 2, Implied),
        op("RLA", 3, 7, AbsoluteY),
        op("NOP", 3, 4, AbsoluteX),
        op("AND", 3, 4, AbsoluteX),
        op("ROL", 3, 7, AbsoluteX),
        op("RLA", 3, 7, AbsoluteX),
        // 0x40
        op("RTI", 1, 6, Implied),
        op("EOR", 2, 6, IndirectX),
        op("KIL", 1, 2, Implied),
        op("SRE", 2, 8, IndirectX),
        op("NOP", 2, 3, ZeroPage),
        op("EOR", 2, 3, ZeroPage),
        op("LSR", 2, 5, ZeroPage),
        op("SRE", 2, 5, ZeroPage),
        op("PHA", 1, 3, Implied),
        op("EOR", 2, 2, Immediate),
        op("LSR", 1, 2, Accumulator),
        op("ALR", 2, 2, Immediate),
        op("JMP", 3, 3, Absolute),
        op("EOR", 3, 4, Absolute),
        op("LSR", 3, 6, Absolute),
        op("SRE", 3, 6, Absolute),
        // 0x50
        op("BVC", 2, 2, Relative),
        op("EOR", 2, 5, IndirectY),
        op("KIL", 1, 2, Implied),
        op("SRE", 2, 8, IndirectY),
        op("NOP", 2, 4, ZeroPageX),
        op("EOR", 2, 4, ZeroPageX),
        op("LSR", 2, 6, ZeroPageX),
        op("SRE", 2, 6, ZeroPageX),
        op("CLI", 1, 2, Implied),
        op("EOR", 3, 4, AbsoluteY),
        op("NOP", 1, 2, Implied),
        op("SRE", 3, 7, AbsoluteY),
        op("NOP", 3, 4, AbsoluteX),
        op("EOR", 3, 4, AbsoluteX),
        op("LSR", 3, 7, AbsoluteX),
        op("SRE", 3, 7, AbsoluteX),
        // 0x60
        op("RTS", 1, 6, Implied),
        op("ADC", 2, 6, IndirectX),
        op("KIL", 1, 2, Implied),
        op("RRA", 2, 8, IndirectX),
        op("NOP", 2, 3, ZeroPage),
        op("ADC", 2, 3, ZeroPage),
        op("ROR", 2, 5, ZeroPage),
        op("RRA", 2, 5, ZeroPage),
        op("PLA", 1, 4, Implied),
        op("ADC", 2, 2, Immediate),
        op("ROR", 1, 2, Accumulator),
        op("ARR", 2, 2, Immediate),
        op("JMP", 3, 5, Indirect),
        op("ADC", 3, 4, Absolute),
        op("ROR", 3, 6, Absolute),
        op("RRA", 3, 6, Absolute),
        // 0x70
        op("BVS", 2, 2, Relative),
        op("ADC", 2, 5, IndirectY),
        op("KIL", 1, 2, Implied),
        op("RRA", 2, 8, IndirectY),
        op("NOP", 2, 4, ZeroPageX),
        op("ADC", 2, 4, ZeroPageX),
        op("ROR", 2, 6, ZeroPageX),
        op("RRA", 2, 6, ZeroPageX),
        op("SEI", 1, 2, Implied),
        op("ADC", 3, 4, AbsoluteY),
        op("NOP", 1, 2, Implied),
        op("RRA", 3, 7, AbsoluteY),
        op("NOP", 3, 4, AbsoluteX),
        op("ADC", 3, 4, AbsoluteX),
        op("ROR", 3, 7, AbsoluteX),
        op("RRA", 3, 7, AbsoluteX),
        // 0x80
        op("NOP", 2, 2, Immediate),
        op("STA", 2, 6, IndirectX),
        op("NOP", 2, 2, Immediate),
        op("SAX", 2, 6, IndirectX),
        op("STY", 2, 3, ZeroPage),
        op("STA", 2, 3, ZeroPage),
        op("STX", 2, 3, ZeroPage),
        op("SAX", 2, 3, ZeroPage),
        op("DEY", 1, 2, Implied),
        op("NOP", 2, 2, Immediate),
        op("TXA", 1, 2, Implied),
        op("XAA", 2, 2, Immediate),
        op("STY", 3, 4, Absolute),
        op("STA", 3, 4, Absolute),
        op("STX", 3, 4, Absolute),
        op("SAX", 3, 4, Absolute),
        // 0x90
        op("BCC", 2, 2, Relative),
        op("STA", 2, 6, IndirectY),
        op("KIL", 1, 2, Implied),
        op("AHX", 2, 6, IndirectY),
        op("STY", 2, 4, ZeroPageX),
        op("STA", 2, 4, ZeroPageX),
        op("STX", 2, 4, ZeroPageY),
        op("SAX", 2, 4, ZeroPageY),
        op("TYA", 1, 2, Implied),
        op("STA", 3, 5, AbsoluteY),
        op("TXS", 1, 2, Implied),
        op("TAS", 3, 5, AbsoluteY),
        op("SHY", 3, 5, AbsoluteX),
        op("STA", 3, 5, AbsoluteX),
        op("SHX", 3, 5, AbsoluteY),
        op("AHX", 3, 5, AbsoluteY),
        // 0xA0
        op("LDY", 2, 2, Immediate),
        op("LDA", 2, 6, IndirectX),
        op("LDX", 2, 2, Immediate),
        op("LAX", 2, 6, IndirectX),
        op("LDY", 2, 3, ZeroPage),
        op("LDA", 2, 3, ZeroPage),
        op("LDX", 2, 3, ZeroPage),
        op("LAX", 2, 3, ZeroPage),
        op("TAY", 1, 2, Implied),
        op("LDA", 2, 2, Immediate),
        op("TAX", 1, 2, Implied),
        op("LAX", 2, 2, Immediate),
        op("LDY", 3, 4, Absolute),
        op("LDA", 3, 4, Absolute),
        op("LDX", 3, 4, Absolute),
        op("LAX", 3, 4, Absolute),
        // 0xB0
        op("BCS", 2, 2, Relative),
        op("LDA", 2, 5, IndirectY),
        op("KIL", 1, 2, Implied),
        op("LAX", 2, 5, IndirectY),
        op("LDY", 2, 4, ZeroPageX),
        op("LDA", 2, 4, ZeroPageX),
        op("LDX", 2, 4, ZeroPageY),
        op("LAX", 2, 4, ZeroPageY),
        op("CLV", 1, 2, Implied),
        op("LDA", 3, 4, AbsoluteY),
        op("TSX", 1, 2, Implied),
        op("LAS", 3, 4, AbsoluteY),
        op("LDY", 3, 4, AbsoluteX),
        op("LDA", 3, 4, AbsoluteX),
        op("LDX", 3, 4, AbsoluteY),
        op("LAX", 3, 4, AbsoluteY),
        // 0xC0
        op("CPY", 2, 2, Immediate),
        op("CMP", 2, 6, IndirectX),
        op("NOP", 2, 2, Immediate),
        op("DCP", 2, 8, IndirectX),
        op("CPY", 2, 3, ZeroPage),
        op("CMP", 2, 3, ZeroPage),
        op("DEC", 2, 5, ZeroPage),
        op("DCP", 2, 5, ZeroPage),
        op("INY", 1, 2, Implied),
        op("CMP", 2, 2, Immediate),
        op("DEX", 1, 2, Implied),
        op("AXS", 2, 2, Immediate),
        op("CPY", 3, 4, Absolute),
        op("CMP", 3, 4, Absolute),
        op("DEC", 3, 6, Absolute),
        op("DCP", 3, 6, Absolute),
        // 0xD0
        op("BNE", 2, 2, Relative),
        op("CMP", 2, 5, IndirectY),
        op("KIL", 1, 2, Implied),
        op("DCP", 2, 8, IndirectY),
        op("NOP", 2, 4, ZeroPageX),
        op("CMP", 2, 4, ZeroPageX),
        op("DEC", 2, 6, ZeroPageX),
        op("DCP", 2, 6, ZeroPageX),
        op("CLD", 1, 2, Implied),
        op("CMP", 3, 4, AbsoluteY),
        op("NOP", 1, 2, Implied),
        op("DCP", 3, 7, AbsoluteY),
        op("NOP", 3, 4, AbsoluteX),
        op("CMP", 3, 4, AbsoluteX),
        op("DEC", 3, 7, AbsoluteX),
        op("DCP", 3, 7, AbsoluteX),
        // 0xE0
        op("CPX", 2, 2, Immediate),
        op("SBC", 2, 6, IndirectX),
        op("NOP", 2, 2, Immediate),
        op("ISB", 2, 8, IndirectX),
        op("CPX", 2, 3, ZeroPage),
        op("SBC", 2, 3, ZeroPage),
        op("INC", 2, 5, ZeroPage),
        op("ISB", 2, 5, ZeroPage),
        op("INX", 1, 2, Implied),
        op("SBC", 2, 2, Immediate),
        op("NOP", 1, 2, Implied),
        op("SBC", 2, 2, Immediate),
        op("CPX", 3, 4, Absolute),
        op("SBC", 3, 4, Absolute),
        op("INC", 3, 6, Absolute),
        op("ISB", 3, 6, Absolute),
        // 0xF0
        op("BEQ", 2, 2, Relative),
        op("SBC", 2, 5, IndirectY),
        op("KIL", 1, 2, Implied),
        op("ISB", 2, 8, IndirectY),
        op("NOP", 2, 4, ZeroPageX),
        op("SBC", 2, 4, ZeroPageX),
        op("INC", 2, 6, ZeroPageX),
        op("ISB", 2, 6, ZeroPageX),
        op("SED", 1, 2, Implied),
        op("SBC", 3, 4, AbsoluteY),
        op("NOP", 1, 2, Implied),
        op("ISB", 3, 7, AbsoluteY),
        op("NOP", 3, 4, AbsoluteX),
        op("SBC", 3, 4, AbsoluteX),
        op("INC", 3, 7, AbsoluteX),
        op("ISB", 3, 7, AbsoluteX),
    ]
};
